[package]
name = "cirrus-backend"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.5"
hyper = { version = "0.14", features = ["full"] }
tokio = { version = "1.20", features = ["full"] }
tower = "0.4"
anyhow = "1.0"
reqwest = { version = "0.11", features = ["rustls", "json"], default-features = false }