name: backend

on:
  push:
    paths:
      - "backend/**"
      - ".github/**"
  pull_request:
    paths:
      - "backend/**"
      - ".github/**"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Build
      run: go build -v ./...
      working-directory: backend

    - name: Unit test
      run: go test -v ./...
      working-directory: backend

    - name: Integration test
      run: ./run.sh
      working-directory: backend/tests
