name: CI Backend

on: push

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-go@v1
      with:
        go-version: '1.13'
    - name: check formatting
      run: test -z $(gofmt -l -s backend/**/*.go)
    - run: go build -v ./...
      working-directory: ./backend
    - run: go test -v ./...
      working-directory: ./backend
