name: CI Backend

on: push

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-go@v1
      with:
        go-version: '1.13'
    - name: check formatting
      run: test -z $(gofmt -l -s backend/**/*.go)
    - run: go build -v ./...
      working-directory: ./backend
    - run: go test -coverprofile=coverage.txt -coverpkg=./... -covermode=count ./...
      working-directory: ./backend
    - uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./backend/coverage.txt